#[build-system]
#requires = ["setuptools>=61.0"]
#build-backend = "setuptools.build_meta"

[project]
name =  "python-utils"
authors = [ {name = "Christina O'Donnell", email = "cdo@mutix.org"}, ]
version = "0.1.0"
dependencies = [
  "pypandoc >= 1.13",
  "pyyaml >= 6.0.2"
]

[project.scripts]
cdo-restic = "cdo_restic:main"
dirsplit = "dirsplit:main"
line-set-diff = "line_set_diff:main"
git-least-diff = "git_least_diff:main"
git-credentials-read = "git_credentials_read:main"
archive = "archive:main"
